name: myroutine
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  audioplayers: ^5.2.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  sound_mode: ^3.0.0
  sqflite: ^2.3.0
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/chime.mp3
    - assets/alert_notification.mp3
    - assets/positive_tone_1.mp3
    - assets/positive_tone_2.mp3

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
  